name: Deploy to Firebase Hosting on Merge

on:
  push:
    branches: [ "main" ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Node - Good practice to specify a version
      - name: Setup Node.js
        uses: actions/setup-node@v4 # Use a specific version like setup-node@v4
        with:
          node-version: '18' # Or your project's required Node version

      # Install frontend dependencies
      - name: Install Frontend Dependencies
        run: npm install
        working-directory: ./frontend # Specify working directory

      # Build frontend WITH environment variables
      - name: Build Frontend
        run: npm run build
        working-directory: ./frontend # Specify working directory
        env: # <-- Add this env block to inject secrets into the build process
          VITE_FIREBASE_API_KEY: ${{ secrets.VITE_FIREBASE_API_KEY }}
          VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}
          VITE_FIREBASE_PROJECT_ID: ${{ secrets.VITE_FIREBASE_PROJECT_ID }}
          VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}
          VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}
          VITE_FIREBASE_APP_ID: ${{ secrets.VITE_FIREBASE_APP_ID }}
          VITE_FIREBASE_MEASUREMENT_ID: ${{ secrets.VITE_FIREBASE_MEASUREMENT_ID }}
          VITE_GOOGLE_CLIENT_ID: ${{ secrets.VITE_GOOGLE_CLIENT_ID }}
          # Add any other VITE_ variables your app needs from secrets

      # Deploy to Firebase Hosting
      - name: Deploy to Firebase Hosting Live Channel
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_CAMPUS_CONNECT_B87D4 }} # Ensure this secret name is correct
          projectId: campus-connect-b87d4
          channelId: live